### ISSUE TITLE
Unable to use on ports other than 443

### ISSUE THREAD

**Issue by jgimenez** [WICG/sms-one-time-codes#3]
The Protocol and port number are hard-coded in the specification. Was this done on purpose?

**Comment by hober** [comment]
The message syntax hardcodes the scheme of the origin, true. The syntax is as simple as possible, to maximize adoption and minimize interoperability problems.

But [§ 2.1. Usage](https://wicg.github.io/sms-one-time-codes/#usage) allows User Agents to assist the user with filling codes on sites which are same site but not same origin with the code's origin. So if the user gets a message specifying "@example.com #123456", browsers could fill 123456 on https://example.com:8080, because that origin is same-site as https://example.com.

**Comment by jgimenez** [comment]
Great, thanks!
